name: Main CI
on:
  pull_request:
    branches:
      - main
jobs:
  all-status-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - action-lint
      - yaml-lint
      - build-test
      - type-test
      - lint-test
      - jest-test
    steps:
      - uses: actions/checkout@v4
      - name: Check all-status-check
        run: |
          diff \
            <(yq ".jobs | del(.all-status-check) | keys.[]" .github/workflows/ci.yml) \
            <(yq ".jobs.all-status-check.needs.[]" .github/workflows/ci.yml)

  action-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@a5524e1c19e62881d79c1f1b9b6f09f16356e281 # v1.65.2
        with:
          level: warning
          fail_level: warning

  yaml-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-yamllint@1dca3ad811867be18fbe293a9818d715a6c2cd46 # v1.20.0
        with:
          level: warning
          fail_level: warning
          yamllint_flags: "-c .yamllint ."

  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: shiron-dev/actions/setup-node@9a546a8db3c1e8c45a10dbfddc64f50cfc8f061c # v1.3.2
      - name: Run install
        run: |
          pnpm install --frozen-lockfile
      - name: Run build
        run: pnpm expo export --platform web

  type-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: shiron-dev/actions/setup-node@9a546a8db3c1e8c45a10dbfddc64f50cfc8f061c # v1.3.2
      - name: Run install
        run: |
          pnpm install --frozen-lockfile
      - name: Run typecheck
        run: pnpm run typecheck

  lint-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: shiron-dev/actions/setup-node@9a546a8db3c1e8c45a10dbfddc64f50cfc8f061c # v1.3.2
      - name: Run install
        run: |
          pnpm install --frozen-lockfile
      - name: Run lint
        run: pnpm run lint

  jest-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: shiron-dev/actions/setup-node@9a546a8db3c1e8c45a10dbfddc64f50cfc8f061c # v1.3.2
      - name: Run install
        run: |
          pnpm install --frozen-lockfile
      - name: Run test
        run: pnpm jest
